# Generated by Django 6.0.5 on 2026-06-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otpcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='accounts_ot_phone_c9778d_idx',
            old_name='accounts_pa_phone_afd0c0_idx',
        ),
    ]
