# Generated by Django 6.0.5 on 2026-06-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_accounts_pa_phone_afd0c0_idx_accounts_ot_phone_c9778d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification'), ('email_verification', 'Email Verification')], default='password_reset', max_length=30),
        ),
    ]
