# Generated by Django 6.0.5 on 2026-06-22 01:17

from django.db import migrations, models


def vip_users_to_user(apps, schema_editor):
    """Fold any retired vip_user accounts into the plain user role."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="vip_user").update(role="user")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_otpcode_purpose'),
    ]

    operations = [
        migrations.RunPython(vip_users_to_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
