# Generated by Django 6.0.5 on 2026-06-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification'), ('email_verification', 'Email Verification'), ('login_2fa', 'Login Two-Factor')], default='password_reset', max_length=30),
        ),
    ]
