# Generated by Django 6.0.5 on 2026-06-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companywallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='company_wallet_balance_non_negative'),
        ),
    ]
