# Generated by Django 6.0.5 on 2026-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(unique=True)),
                ('first_prize', models.CharField(max_length=6)),
                ('three_up', models.CharField(max_length=3)),
                ('two_down', models.CharField(blank=True, max_length=2, null=True)),
                ('source', models.CharField(choices=[('archive', 'Historical Archive'), ('glo', 'GLO Official'), ('sanook', 'Sanook'), ('manual', 'Manual')], max_length=20)),
                ('cross_check_ok', models.BooleanField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-draw_date'],
                'indexes': [models.Index(fields=['-draw_date'], name='lottery_lot_draw_da_a9b915_idx')],
            },
        ),
    ]
