# Generated by Django 6.0.5 on 2026-06-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotterydraw',
            name='two_down',
        ),
    ]
