# Generated by Django 6.0.5 on 2026-05-17 10:11

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(default='+66', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='620717752', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
