# Generated by Django 6.0.5 on 2026-06-27 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidnumberallocation',
            name='number_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 124.', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='number_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 124.', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='rgeneratedgroup',
            name='source_number',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 124.', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='rgenerateditem',
            name='number_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 124.', regex='^\\d{3}$')]),
        ),
    ]
