# Generated by Django 6.0.5 on 2026-06-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ledgernumber',
            constraint=models.CheckConstraint(condition=models.Q(('used_amount__gte', 0)), name='ledger_number_used_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgernumber',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__gte', 0)), name='ledger_number_remaining_non_negative'),
        ),
    ]
