# Generated by Django 6.0.5 on 2026-06-24 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0003_ledgertemplate_ledgertemplatetier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('default_close_time', models.TimeField(blank=True, null=True)),
                ('days_ahead', models.PositiveSmallIntegerField(default=1)),
                ('active_weekdays', models.CharField(default='0,1,2,3,4,5,6', max_length=20)),
                ('code_prefix', models.CharField(blank=True, default='', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='ledgers.ledgertemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_period_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
