# Generated by Django 6.0.5 on 2026-06-24 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0004_periodschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultperiod',
            name='bet_type',
            field=models.CharField(choices=[('3d', '3D'), ('2d', '2D')], default='3d', max_length=2),
        ),
        migrations.AlterField(
            model_name='ledgernumber',
            name='number_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be 2 or 3 digits, example: 24, 124.', regex='^\\d{2,3}$')]),
        ),
        migrations.AlterField(
            model_name='resultperiod',
            name='result_number',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Number must be 2 or 3 digits, example: 24, 124.', regex='^\\d{2,3}$')]),
        ),
    ]
