# Generated by Django 6.0.5 on 2026-06-27 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0005_resultperiod_bet_type_alter_ledgernumber_number_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultperiod',
            name='bet_type',
        ),
        migrations.AlterField(
            model_name='ledgernumber',
            name='number_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 124.', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='resultperiod',
            name='result_number',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Number must be exactly 3 digits, example: 124.', regex='^\\d{3}$')]),
        ),
    ]
