# Generated by Django 6.0.5 on 2026-06-24 12:24

import django.db.models.manager
from django.db import migrations, models

from audit.hashing import GENESIS_HASH, compute_entry_hash, entry_content


def backfill_hash_chain(apps, schema_editor):
    """Hash existing entries in id order so the chain is contiguous."""
    AuditLog = apps.get_model("audit", "AuditLog")
    prev = GENESIS_HASH
    for row in AuditLog.objects.order_by("id").iterator():
        content = entry_content(
            actor_user_id=row.actor_user_id,
            action=row.action,
            target_table=row.target_table,
            target_id=row.target_id,
            old_values=row.old_values,
            new_values=row.new_values,
            ip_address=row.ip_address,
            user_agent=row.user_agent,
            reason=row.reason,
        )
        row.prev_hash = prev
        row.entry_hash = compute_entry_hash(prev, content)
        row.save(update_fields=["prev_hash", "entry_hash"])
        prev = row.entry_hash


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'base_manager_name': 'unsafe_objects'},
        ),
        migrations.AlterModelManagers(
            name='auditlog',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unsafe_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entry_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(backfill_hash_chain, noop_reverse),
    ]
