# Generated by Django 6.0.5 on 2026-06-22 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_depositrequest_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='userwallet',
            constraint=models.CheckConstraint(condition=models.Q(('locked_balance__gte', 0)), name='wallet_locked_balance_non_negative'),
        ),
    ]
