# Generated by Django 6.0.5 on 2026-06-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_idempotencykey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrequest',
            name='proof_image_url',
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_proofs/'),
        ),
    ]
